version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 1550m
    networks:
      - local_network
  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - local_network
  logstash:
    image: docker.elastic.co/logstash/logstash:8.4.2
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    command: logstash -f /usr/share/logstash/config/logstash.conf
    volumes:
      - ./logstash/config:/usr/share/logstash/config
    ports:
      - "5000:5000"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - local_network

volumes:
  elasticsearch_data:

networks:
  local_network:
